repos:
  - repo: https://github.com/tropnikovvl/helm-changelog
    rev: v1.2.1
    hooks:
      - id: helm-changelog
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --directory=example-charts

          # The name of the file that will contain the changes
          - --filename=Changelog.md

          - --verbosity=info
