repos:
  - repo: https://github.com/tropnikovvl/helm-changelog
    rev: v1.3.0
    hooks:
      - id: helm-changelog
        args:
          # Adding commit history to the changelog (default "true")
          - --commit-history=false
          # Directory containing Chart.yaml file (default "./")
          - --directory=example-charts
          # Filename for changelog (default "Changelog.md")
          - --filename=CHANGELOG.md
          # Log level (debug, info, warn, error, fatal, panic) (default "warn")
          - --verbosity=info
