name: Build and Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.16.0'

      - name: Download dependencies
        run: go mod download

      - name: Build & Test
        run: |
          go build -o ./helm-changelog -v ./cmd/
          go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --snapshot --skip-publish --clean
